/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.unir.farmacia.views;

import javax.swing.JOptionPane;

/**
 *
 * @author SoporteTI
 */
public class FarmaciaView extends javax.swing.JFrame {
    
    /**
     * Creates new form FarmaciaView
     */
    public FarmaciaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radiosDistributor = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        typeLabel = new javax.swing.JLabel();
        typeField = new javax.swing.JComboBox<>();
        cantLabel = new javax.swing.JLabel();
        cantField = new javax.swing.JTextField();
        distributorLabel = new javax.swing.JLabel();
        distributorField1 = new javax.swing.JRadioButton();
        distributorField2 = new javax.swing.JRadioButton();
        distributorField3 = new javax.swing.JRadioButton();
        btnClear = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        brandLabel = new javax.swing.JLabel();
        brand1 = new javax.swing.JCheckBox();
        brand2 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("FARMACIA");

        nameLabel.setText("Nombre");

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });
        nameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameFieldKeyTyped(evt);
            }
        });

        typeLabel.setText("Tipo");

        typeField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "analgésico", "analéptico", "anestésico", "antiácido", "antidepresivo", "antibióticos" }));
        typeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeFieldActionPerformed(evt);
            }
        });

        cantLabel.setText("Cantidad");

        cantField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantFieldActionPerformed(evt);
            }
        });
        cantField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cantFieldKeyTyped(evt);
            }
        });

        distributorLabel.setText("Distribuidor");

        radiosDistributor.add(distributorField1);
        distributorField1.setText("Cofarma");

        radiosDistributor.add(distributorField2);
        distributorField2.setText("Empsephar");
        distributorField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distributorField2ActionPerformed(evt);
            }
        });

        radiosDistributor.add(distributorField3);
        distributorField3.setText("Cemefar");

        btnClear.setBackground(new java.awt.Color(255, 153, 153));
        btnClear.setText("Borrar");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(153, 153, 255));
        btnSave.setText("Confirmar");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        brandLabel.setText("Sucursal");

        brand1.setText("Principal");

        brand2.setText("Secundaria");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(brandLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(distributorLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                    .addComponent(cantLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(typeLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameField)
                                    .addComponent(typeField, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cantField)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(distributorField1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(brand1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(distributorField2)
                                            .addComponent(brand2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                        .addComponent(distributorField3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeLabel)
                    .addComponent(typeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(distributorLabel)
                    .addComponent(distributorField1)
                    .addComponent(distributorField2)
                    .addComponent(distributorField3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brandLabel)
                    .addComponent(brand1)
                    .addComponent(brand2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear)
                    .addComponent(btnSave))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void cantFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantFieldActionPerformed

    private void distributorField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distributorField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_distributorField2ActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        nameField.setText("");
        typeField.setSelectedIndex(0);
        radiosDistributor.clearSelection();
        cantField.setText("");
        brand1.setSelected(false);
        brand2.setSelected(false);
        nameField.requestFocus();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if(nameField.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Debe digitar el nombre", "Error",  JOptionPane.ERROR_MESSAGE); 
            nameField.requestFocus();
            return;
        }
        
        if("Seleccione...".equals(String.valueOf(typeField.getSelectedItem()))){
            JOptionPane.showMessageDialog(null, "Debe seleccionar tipo", "Error",  JOptionPane.ERROR_MESSAGE);
            typeField.requestFocus();
            return;
        }
        
        if(cantField.getText().length() == 0 || !validateNumber(cantField.getText()) || Integer.parseInt(cantField.getText()) <= 0){
            JOptionPane.showMessageDialog(null, "Debe digitar la cantidad mayor a cero", "Error",  JOptionPane.ERROR_MESSAGE); 
            cantField.requestFocus();
            return;
        }
        
        if(radiosDistributor.getSelection() == null){
            JOptionPane.showMessageDialog(null, "Debe seleccionar distribuidor", "Error",  JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(!brand1.isSelected() && !brand2.isSelected()){
            JOptionPane.showMessageDialog(null, "Debe seleccionar al menos una sucursal", "Error",  JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String distributorSelected;
        if(distributorField1.isSelected()){
            distributorSelected = distributorField1.getText();
        }else if(distributorField2.isSelected()){
            distributorSelected = distributorField2.getText();
        }else{
            distributorSelected = distributorField3.getText();
        }
        
        PrintView printView = new PrintView(this);
        
        printView.setVisible(true);
        printView.setTitle("Pedido al distribuidor " + distributorSelected);
        printView.setLocationRelativeTo(null);
        
        this.setVisible(false);
        
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void nameFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameFieldKeyTyped
        char c = evt.getKeyChar();
        if (Character.isLetter(c) || Character.isDigit(c) || c == ' ') {
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_nameFieldKeyTyped

    private void cantFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantFieldKeyTyped
        char c = evt.getKeyChar();        
        if (Character.isDigit(c)) {
        }else{
            evt.consume();
        }
    }//GEN-LAST:event_cantFieldKeyTyped

    private void typeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeFieldActionPerformed
        
    }//GEN-LAST:event_typeFieldActionPerformed

    private boolean validateNumber(String text) {
        try {
           Integer.parseInt(text);
           return true;
        } catch (NumberFormatException e) {
           return false;
        }
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JCheckBox brand1;
    public javax.swing.JCheckBox brand2;
    private javax.swing.JLabel brandLabel;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSave;
    public javax.swing.JTextField cantField;
    private javax.swing.JLabel cantLabel;
    public javax.swing.JRadioButton distributorField1;
    public javax.swing.JRadioButton distributorField2;
    public javax.swing.JRadioButton distributorField3;
    private javax.swing.JLabel distributorLabel;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    public javax.swing.ButtonGroup radiosDistributor;
    private javax.swing.JLabel titleLabel;
    public javax.swing.JComboBox<String> typeField;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables
}
